package com.eulernetongt.definitions;

public class LgCommentary {
	
	private String P1, P0, T_POSS, T_NPOSS;	
	
	private static String[] general = {"_P1_ passes",
		"_P0_",
		"_P1_ to _P0_",
		"_P1_ feeds a [wonderful|super|great|brilliant] ball through to _P0_",
		"Delightful little [ball|pass] finds _P0_",
		"Flick on from _P1_ waits for the one two",
		"Neat dummy run and pass",
		"Great footwork, great pass",
		"_P1_ drops the ball at _P0_'s feet",
		"Lofted pass from _P1_ finds its mark",
		"_T_POSS__ are on the attack",
		"_T_NPOSS__ are on the [defence|backfoot]",
		"Outstanding cross finds _P0_",
		"Now _T_POSS__ can mount a challenge through _P0_",
		"Ball in by _P1_ [finds|taken by] _P0_",
		"_P1_ [threads|needles] a great ball to _P0_ ",
		"[Lovely|Superb|Long|Excellent] pass from _P1_ releases _P0_",
		"[Long|Short|Exquisite] floating pass from _P1_ finds _P0_",
		"[Good|Great|Clever] passing move across the pitch and down the [right|left]",
		"[Quick|Well timed] passing [flick|move] down the [left|right]",
		"_P0_ slips past his man and [collects|latches onto] _P1_'s perfectly [timed|weighted] cross.",
		"Another [clever|brilliant|thinking|decent] move [down the wing|thru the centre|across the pitch]",
		"_P0_ [collects|latches onto] _P1_'s [thru ball|pass]",
		"_P1_ [threads|needles] [it|the ball] through the [opponent's|player's] [feet|legs] and finds _P0_",
		"_P1_ [traps|controls] [it|the ball] with his [boot|chest|thigh] and [sends it|passes|flicks on] to _P0_",
		"_P1_ [lobs|heads] the ball towards _P0_",
		"_P0_ twisting and turning again",
		"_P0_ twisting desperately to lose his man",
		"_P0_ rips [up|through] the [centre|midfield]",
		"_P0_ [loses|spins past] his [man|marker]"
		};
	
	private String[] lost_possession = {"It's knocked out by _P1_. _P0_ with the throw.",
			"_P1_ dispossessed",
			"_P1_ dispossessed by _P0_",
			"[_P1_ gives the ball|The ball is given] away [carelessly|cheaply|too easily]",
			"_P1_ takes it over the line. A throw to _T_POSS__",
			"Wild pass by _P1_ results in a throw in for _T_POSS__",
			"_P0_ takes a quick throw in",
			"Long throw in from _P0_",
			"Slide tackle by _P0_ was worthy of topflight baseball.",
			"Heavy ball uncontrolled by _P1_",
			"_P0_ wins the ball with a perfectly timed challenge",
			"Plenty of turnovers here as _T_NPOSS__ give it away",
			"Bad control by _P1_ lets _P0_ steal the ball off him",
			"_P0_ [steals|takes] the ball away from _P1_ with a sliding tackle",
			"Loose ball falls to _P0_",
			"Crunching tackle! _P0_ [comes away with|wins] the ball",
			"_P1_ is left stranded as _P0_ takes the ball",
			"_P0_ makes a great interception",
			"_P0_ gate crashes _P1_'s party and comes away with the prize",
			"Not _P1_'s greatest pass as _P0_ intercepts"
			};
	
	private String[] foul = {"[Oww|Aye korumba], that was a nasty tackle on _P0_",
			"Surely [that's a sending-off offence|_P1_'s going to get booked for that]?",
			"_P1_ [knocks|bowls|crashes] over _P0_ with a double-footed lunge",
			"[Nasty|Crunching] challenge on _P0_",
			"_P0_ gets his legs taken away from him by _P1_",
			"[Slicing|Nasty|Pulverising] challenge by _P1_ on _P0_",
			"Vicious tackle from _P1_ leaves _P0_ lying on the floor in agony",
			"_P1_ clinically takes out _P0_ and leaves him in agony",
			"They don't call _P1_ [The Slayer|The Assassin|Killer|Chopper Reid] for nothing. He's almost killed [the guy|_P0_]!",
			"Ouch! That's got to hurt",
			"_P0_ is on the ground and he ain't smiling",
			"Don't know about _P0_ but that tackle brought tears to my eyes",
			"Extremely high boot from _P1_ sends _P0_ to the ground",
			"_P1_'s black belt in [Karate|Taikwondo|Jujitsu] came in handy then, as he floored _P0_",
			"_P1_ just lost his patience and took _P0_ to the ground.",
			"_P0_ takes the full brunt of _P1_'s challenge.",
			"_P0_ tried to absorb that tackle but it's too much for the ref",
			"Ref played the advantage but eventually had to signal the foul on _P0_",
			"Frustration is setting in, when you start to see fouls like that.",
			"That's what's known as a professional foul",
			"_P0_ tries to run off a nasty challenge",
			"_P1_ with a nasty tackle. Surely he won't get away with that."
			};
	
	private String[] scoring_chance = {"_P0_ infiltrates the defence and [hammers|cracks] it",
			"Deep cross floats in from _P1_ gathered by _P0_ who [slots it towards goal|fires]",
			"_P0_ charges towards goal and [fires|unleashes|stabs|shoots]!",
			"_P0_ spins and shoots",
			"A blazing [shot|strike] from _P0_",
			"_P0_ finds space and tries his luck.",
			"A great opportunity opens up for _T_POSS__",
			"Long ball from _P1_ finds _P0_ at the [near|far] post",
			"_P0_ [has fluffed it|can't control it|snaps a shot] and his miskick heads [toward goal|goalward]",
			"Great first touch heads it goalwards",
			"_P0_'s takes it on the volley and [hammers|nails|plants] it towards goal",
			"_P0_ takes it on the volley from _P1_'s pass pushing goalwards",
			"_P0_ [fires|shoots|blasts it|hammers it] from 22 yards, looks like it's [drifting|curving|spinning|going wide]",
			"_P0_ [drifts|dribbles|runs|strolls|slips|sneaks] into the box, turns inside the defence and fires",
			"_P0_ [drifts|crashes|cuts] in from the [right|left] flank and [strikes|shoots|fires]",
			"_P0_ tries his luck from 30 yards",
			"_P0_ [snaps|arrows|beams] a shot towards [bottom|top] [right|left] corner",
			"_P0_ shoots from close range",
			"[Classy|Great|Inspirational] [pass|ball] from _P1_ sends _P0_ one on one with the [keeper|goalkeeper|goalie]",
			"_P0_'s [scissor|overhead] kick heads towards the [bottom|top] [left|right] hand corner",
			"_P0_ [waltzes|spins|drifts|rips] past two defenders, [dummies|wrong foots] the keeper and [flicks|back heels|clips] the ball [home|towards goal|goalward]",
			"_P1_ lays the ball off to _P0_ who sends a rocket towards goal",
			"_P0_ charging in with a shot",
			"Lay off from _P1_ sets up _T_POSS__ with a chance",
			"_P0_ gets in behind the defence and strikes"
			};
	
	private String[] goal = {"Goal!!!",
			"And the ball is smacked into the back of the net!!!",
			"_P0_ scores!!!",
			"Goal!! Did you see that? [Their goalie|_P1_] certainly didn't.",
			"And the ball [rips|flies|bullets] straight past _P1_ and into the back of the net!!!",
			"The ball [whistles|flies|zips] past _P1_ and it's a goal!!!",
			"_P0_ wheels away in celebration",
			"A truly [mesmerising|great|wonderful|fantastic|brilliant] goal!!",
			"Goal!! _P1_'s [desperate|despairing|stretched] dive can't keep _P0_'s shot out",
			"The ball [lies|is] in the back of the net!!!",
			"Celebrations abound! They won't forget that [goal|strike|shot] in a hurry",
			"_P0_'s dance ignites the fans. He celebrates in his [well known|own] special fashion",
			"Goal! Dipping ball from _P0_ stuns [the keeper|_P1_|_T_NPOSS__]",
			"Outstanding Goal!",
			"Goal! Lady luck obviously supports _T_TT__",
			"[Curving|In swinging|Out swinging|Swerving] ball beats _P1_ to the line. Goal!"
			};
	
	private String[] miss = {"[He's|_P0_'s] [fired|drifted it] wide!",
			"Wandering shot heads awall",
			"_P0_ runs and hides after that [shocking|dreadful|calamitous|disastrous] miss",
			"[He|_P0_] should have squared the ball but went alone and lashed wide",
			"[_P1_|Defender] clears",
			"_P0_ [pushes|curls] ball over",
			"Defender back to block, just as it seemed to open up",
			"_P0_ [thumps|smacks] it into row Z",
			"And the [ball|shot] creeps just past the post",
			"That was never really going in.",
			"Ohh what a chance lost!",
			"Lost opportunities like that can cost _T_POSS__ the match.",
			"It looked so promising for _P0_ then.",
			"He'd done all the hard work but couldn't finish it off",
			"So near yet so far",
			"So nearly going goalward",
			"_T_POSS__ have squandered [a great|their] chance there.",
			"Great run, great delivery but no reward",
			"Lady luck has turned her back on [_P0_|_T_POSS__]",
			"A real let off there for _T_NPOSS__",
			"An audacious attempt, worthy but no payment",
			"There was no gold at the end of that rainbow run",
			"The ball pinballs around the penalty area but finds no way in",
			"That went everywhere except into the net",
			"Into the net but disallowed. The offside flag was raised."
			};
	
	private String[] save = {"Sizzling [strike|shot|] but [the keeper|the goalie|_P1_] has asbestos gloves",
			"_P1_'s fingertips flick it wide",
			"There is a wall out there by the name of _P1_. What a terrific save",
			"Catching practice for _P1_",
			"_P1_ breathes again as the ball [finds its way|deflects] into his arms.",
			"_T_NPOSS__ get a let off here with a superb save by _P1_", 
			"_T_POSS__ denied by a [great|superb|brilliant] [save|parry] by _P1_",
			"Easy pickings for _P1_. He collects the ball",
			"_P1_ forced to tip _P0_'s shot over the crossbar",
			"Great [speed|pace|skill] shown by _P0_ but _P1_ produced a [stunning|superb|just in time] blocking tackle",
			"Low shot taken well to his [right|left] by _P1_",
			"_P1_ gathers it with ease",
			"_P1_ makes a superb reflex save to tip wide",
			"_P1_ [sprints towards|runs at|lunges at] _P0_ and blocks the shot with his [ankle|body|head|torso|leg|boot]",
			"[Great|Brilliant|Sensational|Easy] save by the [keeper|goalie|goalkeeper]",
			"[Saved|Caught|Stopped|Gathered] well by _P1_",
			"Ohh [he|the goalie|the keeper|_P1_] anticipated _P0_'s every move and produced a fine save",
			"That was in by all accounts, but they forgot to tell _P1_, who somehow saved the day",
			"No power in the shot from _P0_. Taken easily by _P1_",
			"[A|That's a] regulation [stop|save] for [_P1_|the keeper]"
			};
	
	private String[] start_match = {"It's a crowd of _AT_ here as the whistle blows",
			"We're under way",
			"The two teams are greeted by a wall of noise as they take to the pitch",
			"[The crowd|_AT_ spectators] roar as the players run out from the tunnel",
			"A cloudless day gives the impression this match is going to sparkle",
			"_AT_ [spectators|fans] can't be wrong. This is the match we have all come to watch",
			"The referee gets the nod from the linesman and we are away",
			"The [battle|struggle|fight|war|combat] begins",
			"The referees are ready, players set, the whistle blows",
			"The fog lifts and away we go"
			};
	
	private String[] half_time = {"It's half time",
			"It's _RE_ at half time.",
			"It's _RE_ at half time. _TL_'s manager has to find something special to spur his team on.",
			"Games like this make managers. _TL_ need inspiration from the top.",
			"The dropped heads tell the story. It's been no picnic here for _TL_.",
			"_TL_'s manager cops a rollicking from the fans as he leaves the dugout",
			"So far _TW_ and their manager have done everything right.",
			"_TL_'s manager is furious with his team's performance this half",
			"One gets the feeling the manager will read _TL_ the riot act",
			"_TL_ will be on the receiving end of their manager's [scolding|wrath]"
			};
	
	private String[] end_match = {"The match is over!",
			"_TW_ are triumphant!!!",
			"The fans boo _TL_ off the pitch",
			"After _MI_ minutes the match ends with a _RE_",
			"The referee checks his watch and blows for full time",
			"Well that's that. It ends _RE_",
			"_TW_'s manager will be delighted with that result"
			};

    private String[] own_goal = {"Ohh no, the ball ricocheted off _P0_ into the net",
            "It's a pinball in the penalty box, finally spinning off _P0_ across the line",
            "Oh that's a great shot and it's deflected off _P0_ and into the back of the net",
            "_P0_ passes the ball back to his goalie. Oh no, the keeper's missed it! It's an own goal by _P0_!",
            "That little misunderstanding has cost _T_TT__ a goal"
    };

}
